spring:
  application:
    name: hotel-api
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_api
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true